-- ============================================================
-- V1__initial_schema.sql
-- Flyway migration: initial multi-tenant schema
-- ============================================================

-- Enable pgcrypto for gen_random_uuid() (Supabase has this by default)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- TENANTS
-- One row per salon / business using the assistant.
-- The primary routing key for inbound WhatsApp messages is
-- whatsapp_phone_number_id (the Meta Business Phone Number ID).
-- ============================================================
CREATE TABLE tenants (
    id                         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Display name of the business
    business_name              VARCHAR(255) NOT NULL,

    -- Meta WhatsApp Business Phone Number ID.
    -- This is the value found at entry[0].changes[0].value.metadata.phone_number_id
    -- in the WhatsApp Cloud API webhook payload and is the canonical routing key.
    whatsapp_phone_number_id   VARCHAR(100) NOT NULL UNIQUE,

    -- Optional human-readable phone number in E.164 format (e.g. +4915112345678)
    whatsapp_display_number    VARCHAR(30),

    -- External calendar integration credential.
    -- In production, store a secret reference (e.g. AWS Secrets Manager key name)
    -- rather than a plaintext API key.
    calendar_api_key           TEXT,

    -- Tenant-specific instructions injected into the LLM system prompt.
    -- Defines the assistant persona, business hours, services offered, etc.
    customized_system_prompt   TEXT        NOT NULL DEFAULT '',

    -- IANA timezone string, e.g. "Europe/Berlin" or "America/New_York"
    timezone                   VARCHAR(100) NOT NULL DEFAULT 'UTC',

    -- BCP 47 language tag, e.g. "en", "de", "tr"
    locale                     VARCHAR(20)  NOT NULL DEFAULT 'en',

    -- Soft-delete / deactivation flag.
    -- Inactive tenants are excluded from routing lookups.
    is_active                  BOOLEAN     NOT NULL DEFAULT TRUE,

    created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- CHAT HISTORY
-- Stores every inbound and outbound message per tenant and
-- customer, providing conversational context for the LLM.
--
-- Isolation dimensions:
--   tenant_id             — ensures cross-tenant data separation
--   customer_phone_number — one customer may contact multiple salons;
--                           history is always scoped to a single tenant
-- ============================================================
CREATE TABLE chat_history (
    id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key to the owning tenant
    tenant_id               UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

    -- Customer's WhatsApp number in E.164 format (the "from" field in inbound messages)
    customer_phone_number   VARCHAR(30) NOT NULL,

    -- Meta-assigned message ID (wamid), useful for deduplication and status tracking
    whatsapp_message_id     VARCHAR(100),

    -- Direction of the message:
    --   inbound  — customer → business (received via webhook)
    --   outbound — business/assistant → customer (sent via Meta Send API)
    direction               VARCHAR(20) NOT NULL CHECK (direction IN ('inbound', 'outbound')),

    -- LLM conversation role:
    --   user      — message from the end customer
    --   assistant — response generated by the AI assistant
    --   system    — injected system prompt or internal note (not shown to the user)
    role                    VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),

    -- Plain text content of the message
    message_text            TEXT,

    -- Full raw webhook payload stored as JSON text for auditability and debugging.
    -- Future: map to JSONB column for native PostgreSQL/Supabase query support.
    raw_payload             TEXT,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Primary access pattern: load recent conversation history for a
-- specific customer at a specific tenant (used to build LLM context window)
CREATE INDEX idx_chat_history_tenant_customer
    ON chat_history (tenant_id, customer_phone_number, created_at DESC);

-- Deduplication check by Meta message ID
CREATE INDEX idx_chat_history_whatsapp_message_id
    ON chat_history (whatsapp_message_id)
    WHERE whatsapp_message_id IS NOT NULL;

-- ============================================================
-- UPDATED_AT TRIGGER (tenants)
-- Automatically keeps updated_at in sync on every row update.
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tenants_updated_at
    BEFORE UPDATE ON tenants
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
